import { XhsCoverStyle } from '../../types';

const ASSET = '/xhs-cover-previews';

export const XHS_COVER_STYLES: XhsCoverStyle[] = [
  {
    id: 'workplace_big_text',
    name: '职场大字',
    previewEmoji: '💼',
    previewImage: `${ASSET}/workplace_big_text.png`,
    category: '职场',
    prompt: '小红书封面设计。\n\n【布局要求】\n- 人物居中，超大文字覆盖整个画面，叠加在人物上\n- 上方文字和下方文字把人物夹在中间\n- 保持原始人像完全不变，只添加文字和装饰，不要修改人脸\n\n【文字样式】\n- 主标题（上方和下方）：纯白色(#FFFFFF)，超粗黑体，巨大\n- 副标题（中间）：黄色(#FFE500)，中等大小\n\n【核心特效 - 必须实现】\n- 文字必须非常大，占画面40%以上，直接覆盖在人物身上\n- 白色文字要有轻微阴影增加立体感\n\n【背景要求】室内办公场景，略微模糊，灰白色调\n\n【氛围】专业、有冲击力、自信、职场感',
  },
  {
    id: 'yellow_pink_banner',
    name: '黄粉横幅',
    previewEmoji: '🎀',
    previewImage: `${ASSET}/yellow_pink_banner.png`,
    category: '创意',
    prompt: '小红书封面设计，3:4竖版。\n\n【文字区域 - 严格限制】\n顶部（画面上方约40%）：只放主标题黄色大字\n底部：粉色横幅铺满整个画面宽度，只放副标题\n人物面部区域：绝对无文字\n\n【主标题样式】\n位置：从画面顶部开始，文字叠压在人物头顶和肩膀\n字体：饱满有力的粗体展示字\n颜色：亮黄色 #FFE135，纯色填充，无描边\n\n【底部粉色横幅】\n位置：画面最底部，从左边缘到右边缘完全铺满\n颜色：亮粉色 #FF2D78，实心色块\n文字：白色居中\n\n【背景】明亮的现代公寓室内实景，温暖木色与白色为主\n\n【人物】居中，温柔自信微笑\n\n【绝对禁止】任何装饰符号、多余文字、修改人物面部',
  },
  {
    id: 'sticker_energy',
    name: '贴纸活力',
    previewEmoji: '⚡',
    previewImage: `${ASSET}/sticker_energy.png`,
    category: '活力',
    prompt: '小红书封面设计。\n\n【布局要求】\n- 主标题在顶部，呈弧形排列\n- 人物在下半部分，做摊手或展示手势\n- 保持原始人像完全不变，只添加文字和装饰，不要修改人脸\n\n【文字样式】\n- 主标题：黑色(#000000)超粗黑体\n- 副标题有黄色(#FFE135)弧形底色\n\n【核心特效 - 必须实现】\n- 人物必须是抠图效果，周围有白色描边(3-5像素)，像贴纸一样贴在背景上\n- 背景是点阵/网点图案\n\n【装饰元素】黄色五角星贴纸⭐ 黄色闪电贴纸⚡\n\n【氛围】活力、年轻、社交媒体感',
  },
  {
    id: 'split_screen_tags',
    name: '分屏标签',
    previewEmoji: '🏷️',
    previewImage: `${ASSET}/split_screen_tags.png`,
    category: '文艺',
    prompt: '小红书封面设计。\n\n【布局要求】\n- 上半部分60%是人物照片，下半部分40%是纯色色块（分屏设计）\n- 保持原始人像完全不变，只添加文字和装饰，不要修改人脸\n\n【文字样式】\n- 顶部文字：黄色(#F7E54D)和浅蓝色(#8DD3E8)混合，手写体\n- 下方色块内文字：黄色手写体，关键词上方加拼音标注\n\n【核心特效 - 必须实现】\n- 下半部分必须是棕色(#6B4C3B)纯色块\n- 人物周围有黄色虚线边框装饰\n- 分割线用斜线(/////)\n\n【氛围】自由、转变、轻松、真实分享',
  },
  {
    id: 'study_room_intellectual',
    name: '书房知性',
    previewEmoji: '📚',
    previewImage: `${ASSET}/study_room_intellectual.png`,
    category: '居家',
    prompt: '小红书封面设计。\n\n【布局要求】\n- 人物居中，半身照\n- 文字分布在人物四周（左上、右上、左下、右下）\n- 文字围绕人物但不遮挡脸部\n- 保持原始人像完全不变，只添加文字和装饰，不要修改人脸\n\n【文字样式】\n- 所有文字使用浅黄色/奶油色(#F5E6A3)\n- 字体：手写体/毛笔风格，字号较大\n\n【核心特效 - 必须实现】\n- 关键词下面加波浪线(~~~)装饰\n- 整体色调温暖柔和\n\n【背景要求】书房场景，有书架，暖色调灯光\n\n【氛围】温暖、智慧、知性',
  },
  {
    id: 'home_motivation',
    name: '居家励志',
    previewEmoji: '🏠',
    previewImage: `${ASSET}/home_motivation.png`,
    category: '居家',
    prompt: '小红书封面设计。\n\n【布局要求】\n- 人物居中，做开放姿势（如张开双臂），大标题分布在人物上下方\n- 只使用中文文字，不要添加英文标签\n- 保持原始人像完全不变，只添加文字和装饰，不要修改人脸\n\n【文字样式】\n- 主标题：亮黄色(#FFF44F)，超粗黑体，非常大\n- 底部小字：白色，用括号()标注\n\n【核心特效 - 必须实现】\n- 文字要非常大，占画面很大比例\n\n【背景要求】居家场景，客厅/餐厅，有家具、绿植，光线明亮温馨\n\n【氛围】鼓励、乐观、生活智慧、温暖',
  },
  {
    id: 'dark_glow',
    name: '深色发光',
    previewEmoji: '✨',
    previewImage: `${ASSET}/dark_glow.png`,
    category: '创意',
    prompt: '小红书封面设计。\n\n【布局要求】\n- 人物在下半部分，积极姿势（如竖大拇指）\n- 大标题在顶部，副标题在中间和底部\n- 保持原始人像完全不变，只添加文字和装饰，不要修改人脸\n\n【文字样式】\n- 主标题：黄色(#FFE135)，粗黑体，有发光效果\n- 问号(?)用黄色，也要发光\n- 副标题：白色(#FFFFFF)，粗体\n\n【核心特效 - 必须实现】\n- 文字必须有外发光效果（glow），发光颜色是淡黄色\n- 背景必须是深色/暗色调\n\n【背景要求】深色背景，有一些暖色光源点缀，整体偏暗\n\n【氛围】希望、积极、突破困境、正能量',
  },
  {
    id: 'dashed_decoration',
    name: '虚线装饰',
    previewEmoji: '〰️',
    previewImage: `${ASSET}/dashed_decoration.png`,
    category: '文艺',
    prompt: '小红书封面设计。\n\n【布局要求】\n- 人物居中，面带微笑，主标题在顶部，副标题在底部用引号包裹\n- 保持原始人像完全不变，只添加文字和装饰\n\n【文字样式】\n- 主标题：白色(#FFFFFF)，粗黑体，大号\n- 副标题：橙色(#FF9500)，用橙色引号(\"\")包裹\n- 只使用中文文字，不要添加英文或拼音\n\n【核心特效 - 必须实现】\n- 白色虚线(- - -)画成半圆弧线，环绕人物头部和肩膀，从左上绕到右下\n\n【背景要求】室内场景，米色/奶油色调，柔和光\n\n【氛围】自信、优雅、温和',
  },
  {
    id: 'hand_drawn_border',
    name: '手绘边框',
    previewEmoji: '🖍️',
    previewImage: `${ASSET}/hand_drawn_border.png`,
    category: '活力',
    prompt: '小红书封面设计。\n\n【布局要求】\n- 人物居中，占画面主体\n- 主标题放在顶部，黑色粗体字，带黄色背景色块\n- 副标题放在人物旁边或下方\n- 保持原始人像完全不变，只添加文字和装饰，不要修改人脸\n\n【文字样式】\n- 主标题：黑色(#1A1A1A)粗黑体，字号超大，文字后面有黄色(#FFD93D)色块作为底色\n- 副标题：黑色粗体\n\n【核心特效 - 必须实现】\n- 人物周围画黄色(#FFD93D)手绘线条描边，像马克笔随意画的轮廓\n- 描边线条要松散、不规则，有手绘感\n\n【装饰元素】左侧添加黄色播放按钮图标，小箭头指向人物\n\n【禁止事项】不要添加任何对话气泡，不要出现与用户内容无关的随意文字\n\n【氛围】活力、有趣、综艺感、年轻化',
  },
  {
    id: 'cozy_home',
    name: '温馨居家',
    previewEmoji: '☕',
    previewImage: `${ASSET}/cozy_home.png`,
    category: '居家',
    prompt: '小红书封面设计。\n\n【布局要求】\n- 人物居中偏右，手持物品（如咖啡杯）\n- 主标题在顶部，底部文字用椭圆高亮\n- 保持原始人像完全不变，只添加文字和装饰，不要修改人脸\n\n【文字样式】\n- 主标题：黄白渐变色(#F5D547)，粗黑体，数字要突出\n- 关键词用黄色椭圆圈起来\n\n【核心特效 - 必须实现】\n- 底部关键词外面画黄色椭圆形边框，椭圆是手绘风格，线条不完全闭合\n\n【背景要求】温馨居家场景，有沙发、木质家具、绿植，暖色调\n\n【氛围】温馨、生活化、平衡、舒适',
  },
  {
    id: 'background_big_text',
    name: '背景大字',
    previewEmoji: '🔤',
    previewImage: `${ASSET}/background_big_text.png`,
    category: '创意',
    prompt: '小红书封面设计。\n\n【布局要求】\n- 超大文字作为背景层，人物在前景\n- 文字要被人物部分遮挡\n- 保持原始人像完全不变，只添加文字和装饰，不要修改人脸\n\n【文字样式】\n- 背景大字：橙色(#FF6B35)，超粗黑体，占画面80%\n- 文字放在人物后面（人物遮挡部分文字）\n- 副标题用【】中括号包裹\n\n【核心特效 - 必须实现】\n- 大字必须在人物后面作为背景，人物覆盖在文字上方\n\n【禁止事项】主标题只出现一次，绝对不要在画面任何位置重复相同文字\n\n【背景要求】浅灰白色背景\n\n【氛围】教学、专业、有冲击力',
  },
  {
    id: 'thinking_question',
    name: '思考提问',
    previewEmoji: '🤔',
    previewImage: `${ASSET}/thinking_question.png`,
    category: '文艺',
    prompt: '小红书封面设计。\n\n【布局要求】\n- 人物在左侧，做思考姿势（手托下巴）\n- 文字散落在右侧和上方，文字排列不规则，有大有小\n- 保持原始人像完全不变，只添加文字和装饰，不要修改人脸\n\n【文字样式】\n- 所有文字使用蓝灰色(#5B7A8A)，字体：毛笔手写体\n- 问号(?)作为重要元素，要大且醒目\n\n【核心特效 - 必须实现】\n- 虚线从人物延伸出来，连接到文字\n- 文字要有毛笔的笔触感\n\n【背景要求】纯白色背景\n\n【氛围】思考、疑问、探讨、理性',
  },
  {
    id: 'neon_contrast',
    name: '霓虹撞色',
    previewEmoji: '🌈',
    previewImage: `${ASSET}/neon_contrast.png`,
    category: '活力',
    prompt: '小红书封面设计。\n\n【布局要求】\n- 人物照片居中，占满大部分画面\n- 整个画面外围有粗边框\n- 主标题在顶部，副标题在底部\n- 保持原始人像完全不变，只添加文字和装饰，不要修改人脸\n\n【文字样式】\n- 主标题：荧光绿色(#7FFF00)，粗黑体，超大号\n- 副标题：荧光绿色(#7FFF00)，包含中文和拼音注释\n- 用大括号{}包裹关键词\n\n【核心特效 - 必须实现】\n- 整个画面外围加粗的荧光粉色(#FF1493)边框，约20-30像素宽\n- 必须使用荧光粉和荧光绿，颜色非常鲜艳\n\n【装饰元素】右上角添加期数标签如\"#01\"，文字旁边加竖线装饰\n\n【氛围】大胆、潮流、Y2K、Z世代',
  },
  {
    id: 'pink_yellow_playful',
    name: '粉黄俏皮',
    previewEmoji: '🌸',
    previewImage: `${ASSET}/pink_yellow_playful.png`,
    category: '活力',
    prompt: '小红书封面设计。\n\n【布局要求】\n- 人物居中，半身照，手势自然\n- 顶部大字英文标题，左侧和右侧分布中文文字\n- 保持原始人像完全不变，只添加文字和装饰，不要修改人脸\n\n【文字样式】\n- 顶部英文：亮黄色(#FFE135)，粗体，字母呈波浪状排列，有动感\n- 左侧中文：粉红色(#FF69B4)，手写体风格，竖排或斜排\n- 右侧中文：亮黄色(#FFE135)，手写体风格\n\n【核心特效 - 必须实现】\n- 英文字母要有波浪起伏效果，不是直线排列\n- 中文文字要有手写的随意感\n\n【装饰元素】可以添加小星星、爱心等可爱装饰\n\n【背景要求】室内场景，背景略微模糊，柔和自然光\n\n【氛围】俏皮、可爱、亲和、年轻活力',
  },
  {
    id: 'professional_woman',
    name: '职业男女',
    previewEmoji: '👩‍💻',
    previewImage: `${ASSET}/professional_woman.png`,
    category: '职场',
    prompt: '小红书封面设计。\n\n【布局要求】\n- 人物居中，主标题在顶部，副标题在底部，用引号包裹\n- 保持原始人像完全不变，只添加文字和装饰，不要修改人脸\n\n【文字样式】\n- 主标题：奶黄色(#E8D57E)，粗黑体，超大号\n- 副标题：奶黄色，用红色引号(\"\")包裹\n\n【核心特效 - 必须实现】\n- 红色(#C41E3A)虚线弧线横穿画面\n- 红色方块引号装饰\"\"\n\n【背景要求】室内场景，暖木色调\n\n【氛围】自信、赋能、专业、女性力量',
  },
  {
    id: 'outdoor_handwriting',
    name: '户外手写',
    previewEmoji: '🌿',
    previewImage: `${ASSET}/outdoor_handwriting.png`,
    category: '文艺',
    prompt: '小红书封面设计。\n\n【布局要求】\n- 人物放在画面左侧，约占30%宽度\n- 文字放在右侧，采用竖排排列（从上到下阅读）\n- 文字分成两列纵向分布\n- 保持原始人像完全不变，只添加文字和装饰，不要修改人脸\n\n【文字样式】\n- 所有文字使用黄色(#F7E03C)\n- 字体：毛笔手写体/书法风格\n- 笔触要有毛笔的粗细变化和飞白效果\n\n【核心特效 - 必须实现】\n- 文字必须是竖排排列\n- 添加黄色弧形箭头作为装饰，连接文字元素\n\n【背景要求】蓝天白云，绿色草地，光线明亮\n\n【氛围】自由、清新、治愈、文艺',
  },
  {
    id: 'multi_layer_layout',
    name: '多层排版',
    previewEmoji: '📐',
    previewImage: `${ASSET}/multi_layer_layout.png`,
    category: '职场',
    prompt: '小红书封面设计。\n\n【布局要求】\n- 人物放在右侧，约占60%画面\n- 文字分多层排布在左侧和顶部\n- 采用杂志编辑式的不对称布局\n- 保持原始人像完全不变，只添加文字和装饰，不要修改人脸\n\n【文字样式】\n- 主标题：黑色(#1A1A1A)无衬线粗体\n- 强调词：橙红色(#FF4D4D)\n- 左侧边缘有竖排小字\n\n【核心特效 - 必须实现】\n- 文字大小层次分明，有大有小\n- 橙红色感叹号(!)作为视觉焦点\n\n【背景要求】浅灰色纯色背景\n\n【氛围】专业、编辑感、知性',
  },
  {
    id: 'professional_clean',
    name: '专业简洁',
    previewEmoji: '🎯',
    previewImage: `${ASSET}/professional_clean.png`,
    category: '职场',
    prompt: '小红书封面设计。\n\n【布局要求】\n- 人物居中偏下，全身照或大半身照，主标题在顶部简洁有力\n- 保持原始人像完全不变，只添加文字和装饰，不要修改人脸\n\n【文字样式】\n- 主标题：纯白色(#FFFFFF)，粗黑体，大字号\n- 文字排列整齐，左对齐或居中，字体简洁现代，无装饰\n\n【核心特效 - 必须实现】\n- 文字要有轻微阴影或描边，确保在背景上清晰可见\n- 不要添加过多装饰，保持简洁专业\n\n【背景要求】现代办公室场景，有玻璃隔断，暖色调木质元素，背景略微虚化\n\n【氛围】专业、自信、现代、干练、高级感',
  },
];

export const XHS_STYLE_CATEGORIES = [
  { label: '职场', ids: ['workplace_big_text', 'professional_woman', 'professional_clean', 'multi_layer_layout'] },
  { label: '居家', ids: ['home_motivation', 'cozy_home', 'study_room_intellectual'] },
  { label: '活力', ids: ['sticker_energy', 'pink_yellow_playful', 'neon_contrast', 'hand_drawn_border'] },
  { label: '文艺', ids: ['outdoor_handwriting', 'thinking_question', 'split_screen_tags', 'dashed_decoration'] },
  { label: '创意', ids: ['yellow_pink_banner', 'dark_glow', 'background_big_text'] },
];
