import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync(new URL('./SmartFactoryKnowledgeManager.tsx', import.meta.url), 'utf8');
const sourceMap = readFileSync(new URL('./difyAppStudioSourceMap.ts', import.meta.url), 'utf8');

test('knowledge manager owns Dify-style dataset list and detail management', () => {
  assert.match(source, /SmartFactoryKnowledgeManager/);
  assert.match(source, /知识库/);
  assert.match(source, /知识库列表/);
  assert.match(source, /创建知识库/);
  assert.match(source, /导入数据源/);
  assert.match(source, /删除知识库/);
  assert.match(source, /确认删除知识库/);
  assert.match(source, /onDeleteKnowledgeBase/);
  assert.match(source, /openImportTarget/);
  assert.match(source, /搜索知识库/);
  assert.match(source, /返回知识库列表/);
  assert.match(source, /DATASET/);
  assert.match(source, /文档/);
  assert.match(source, /上传并训练/);
  assert.match(source, /文件上传/);
  assert.match(source, /开始训练/);
  assert.match(source, /分段策略/);
  assert.match(source, /FAQ型/);
  assert.match(source, /最大分段字符/);
  assert.match(source, /训练失败/);
  assert.match(source, /错误原因/);
  assert.match(source, /召回测试/);
  assert.match(source, /运行召回测试/);
  assert.match(source, /Top K/);
  assert.match(source, /Score 阈值/);
  assert.match(source, /最大上下文字符/);
  assert.match(source, /Embedding 模型/);
  assert.match(source, /Rerank 模型/);
  assert.match(source, /知识库训练模型/);
  assert.match(source, /知识库设置/);
  assert.match(source, /保存设置/);
  assert.match(source, /文档管理/);
  assert.match(source, /知识库 API/);
  assert.match(source, /PATCH \/api\/smart-factory\/knowledge-bases/);
  assert.match(source, /POST \/api\/smart-factory\/knowledge-documents/);
  assert.match(source, /POST \/api\/smart-factory\/knowledge-search/);
  assert.match(sourceMap, /datasets\/page\.tsx/);
  assert.match(sourceMap, /documents\/page\.tsx/);
  assert.match(sourceMap, /hitTesting\/page\.tsx/);
  assert.match(sourceMap, /settings\/page\.tsx/);
  assert.match(sourceMap, /api\/page\.tsx/);
  assert.doesNotMatch(source, /text-\[24px\][^>]*>知识库/);
  assert.doesNotMatch(source, /Dify datasets source-mapped/);
});
