import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync(new URL('./SmartFactoryPanel.tsx', import.meta.url), 'utf8');
const sourceMap = readFileSync(new URL('./difyAppStudioSourceMap.ts', import.meta.url), 'utf8');

test('smart factory panel reads and displays runtime configuration', () => {
  // 2026-07-08 商用化:Dify 源码映射只允许留在 difyAppStudioSourceMap.ts 作移植档案,
  // 商户可见的面板源码里不得再出现任何 Dify/source-mapped/源码映射标注(业主截图投诉)
  assert.doesNotMatch(source, /Dify/i);
  assert.doesNotMatch(source, /source-mapped/);
  assert.doesNotMatch(source, /源码映射/);
  assert.doesNotMatch(source, /DIFY_APP_STUDIO_SOURCE_PATHS/);
  assert.doesNotMatch(source, /DIFY_APP_STUDIO_MIGRATION_MODE/);
  assert.match(sourceMap, /web\/app\/components\/workflow\/nodes\/agent-v2\/panel\.tsx/);
  assert.match(sourceMap, /web\/app\/components\/workflow\/nodes\/agent-v2\/components\/agent-task-field\.tsx/);
  assert.match(sourceMap, /web\/app\/components\/base\/prompt-editor\/index\.tsx/);
  assert.match(sourceMap, /web\/app\/components\/workflow\/panel\/debug-and-preview\/index\.tsx/);
  assert.match(sourceMap, /web\/app\/\(commonLayout\)\/datasets\/page\.tsx/);
  assert.match(sourceMap, /web\/app\/\(commonLayout\)\/datasets\/\(datasetDetailLayout\)\/\[datasetId\]\/documents\/page\.tsx/);
  assert.match(sourceMap, /599d92ef6b59adcaffc82f5231391749fa1ef94c/);
  assert.match(source, /SmartFactoryKnowledgeManager/);
  assert.match(source, /fetchSmartFactoryConfig/);
  assert.match(source, /sendSmartFactoryChat/);
  assert.match(source, /addSmartFactoryKnowledgeDocument/);
  assert.doesNotMatch(source, /saveSmartFactoryModelProvider/);
  assert.doesNotMatch(source, /testSmartFactoryModelProvider/);
  assert.doesNotMatch(source, /fetchSmartFactoryModelProviderPresets/);
  assert.doesNotMatch(source, /deleteSmartFactoryModelProvider/);
  assert.match(source, /createSmartFactoryAgent/);
  assert.match(source, /updateSmartFactoryAgent/);
  assert.match(source, /publishSmartFactoryAgent/);
  assert.match(source, /createSmartFactoryKnowledgeBase/);
  assert.match(source, /updateSmartFactoryKnowledgeBase/);
  assert.match(source, /retrainSmartFactoryKnowledgeDocument/);
  assert.match(source, /deleteSmartFactoryKnowledgeDocument/);
  assert.match(source, /searchSmartFactoryKnowledge/);
  assert.match(source, /saveSmartFactoryTool/);
  assert.match(source, /testSmartFactoryTool/);
  assert.match(source, /deleteSmartFactoryTool/);
  assert.match(source, /useEffect/);
  assert.match(source, /对话/);
  assert.match(source, /智能体/);
  assert.match(source, /发布智能体/);
  assert.match(source, /调试与预览/);
  assert.match(source, /模型/);
  assert.match(source, /知识库/);
  assert.match(source, /工作室/);
  assert.match(source, /智能工厂主导航/);
  assert.match(source, /renderAreaFrame/);
  assert.match(source, /管理知识库/);
  assert.match(source, /知识库创建、文档上传、训练和召回测试已移到独立知识库页面/);
  assert.match(source, /工具/);
  assert.match(source, /CLI 工具/);
  assert.match(source, /日志与标注/);
  assert.match(source, /监测/);
  assert.match(source, /documentCount/);
  assert.match(source, /knowledgeChunkStrategy/);
  assert.match(source, /knowledgeRetrievalTopK/);
  assert.match(source, /retrievalPolicy/);
  assert.match(source, /变量/);
  assert.match(source, /元数据过滤/);
  assert.match(source, /视觉/);
  assert.match(source, /Agent 设置/);
  assert.match(source, /发布前检查|发布/);
  assert.match(source, /引用来源/);
  assert.match(source, /工具结果/);
  assert.match(source, /Trace/);
  assert.match(source, /创建应用/);
  assert.match(source, /应用列表/);
  assert.match(source, /返回应用列表/);
  assert.match(source, /智能体工作室/);
  assert.match(source, /访问 API/);
  assert.match(source, /POST \/api\/smart-factory\/chat/);
  assert.match(source, /搜索应用/);
  assert.match(source, /统一模型中心/);
  assert.match(source, /设置中心 \/ 统一模型中心/);
  assert.match(source, /模型中心统一管理/);
  assert.match(source, /这里只做绑定和运行选择/);
  assert.doesNotMatch(source, /id: 'models'/);
  assert.doesNotMatch(source, /renderModelsContent/);
  assert.doesNotMatch(source, /Dify model config source-mapped/);
  assert.doesNotMatch(source, /可用模型供应商/);
  assert.doesNotMatch(source, /模型能力矩阵/);
  assert.match(source, /对话模型/);
  assert.match(source, /Embedding/);
  assert.match(source, /Rerank/);
  assert.match(source, /图片生成/);
  assert.match(source, /视频生成/);
  assert.doesNotMatch(source, /安装模型供应商/);
  assert.doesNotMatch(source, /添加供应商模板/);
  assert.doesNotMatch(source, /使用模板配置/);
  assert.doesNotMatch(source, /保存供应商配置/);
  assert.doesNotMatch(source, /配置供应商/);
  assert.doesNotMatch(source, /删除供应商/);
  assert.doesNotMatch(source, /默认模型/);
  assert.doesNotMatch(source, /备用模型/);
  assert.match(source, /从统一模型中心选择当前智能体运行模型/);
  assert.match(source, /这里仅为当前智能体选择对话模型/);
  assert.match(source, /Base URL/);
assert.match(source, /updateSmartFactoryKnowledgeBase\(activeKnowledgeBaseId,[\s\S]*embeddingModel: parseModelOptionValue\(knowledgeEmbeddingModel\)/);
assert.match(source, /updateSmartFactoryKnowledgeBase\(activeKnowledgeBaseId,[\s\S]*rerankModel: parseModelOptionValue\(knowledgeRerankModel\)/);
assert.match(source, /SMART_FACTORY_CLI_FEISHU_CREATE_SHEET_COMMAND/);
assert.doesNotMatch(source, /支持飞书、HTTP API、Shell CLI 等工具类型/);
  assert.match(source, /工具模板/);
  assert.match(source, /飞书表格/);
  assert.match(source, /HTTP API/);
  assert.match(source, /Shell CLI/);
  assert.match(source, /图片生成/);
  assert.match(source, /视频生成/);
  assert.match(source, /Seedance Fast 视频/);
  assert.match(source, /media\.generate_image/);
  assert.match(source, /media\.generate_video/);
  assert.match(source, /generate_seedance_fast_video/);
  assert.match(source, /bytedance\/seedance-2-fast/);
  assert.match(source, /getToolVisual/);
  assert.match(source, /参数 Schema/);
  assert.match(source, /删除工具/);
  assert.doesNotMatch(source, /const renderHome/);
  assert.doesNotMatch(source, /const renderKnowledgeArea\s*=/);
  assert.match(source, /metadataFilters/);
  assert.match(source, /variables/);
  assert.match(source, /vision/);
  assert.match(source, /updateSmartFactoryAgent/);
  assert.doesNotMatch(source, /真实飞书已接入/);
  assert.doesNotMatch(source, /轻量版/);
  assert.doesNotMatch(source, /<button[^>]*>上传并训练/);
});
